Travel1.0.0/Travel.UI/Areas/Report/Controllers/ManagementController.cs
using System;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Hosting;
using Travel.Business.Derived;
using Travel.Data.Entities.Identity;
using Travel.Model.Factories;
using Travel.Service.Interface;

namespace TastyQueen.UI.Areas.Report.Controllers
{
    [Area("Report")]
    [Authorize(Roles = "Admin")]
    public class ManagementController : Controller
    {
        private readonly BllReport _bllReport;
        private readonly IConfiguration _configuration;
        private readonly IHostingEnvironment _hostingEnvironment;
        private readonly UserManager<ApplicationUser> _userManager;

        public ManagementController(UserManager<ApplicationUser> userManager, IReportService iReportService,
            IModelFactory iModelFactory,
            IHostingEnvironment hostingEnvironment, IConfiguration Configuration)
        {
            _bllReport = new BllReport(iReportService, iModelFactory, Configuration);
            _hostingEnvironment = hostingEnvironment;
            _configuration = Configuration;
            _userManager = userManager;
        }

        public async Task<IActionResult> Index()
        {
            return View();
        }

        public async Task<IActionResult> Clients()
        {
            var applicationuser = await _userManager.GetUserAsync(HttpContext.User);
            ViewBag.ChefId = applicationuser.B2BInformation != null ? applicationuser.B2BInformation.Id : "";
            return View();
        }

        public async Task<IActionResult> Payments()
        {
            var applicationuser = await _userManager.GetUserAsync(HttpContext.User);
            ViewBag.ChefId = applicationuser.B2BInformation != null ? applicationuser.B2BInformation.Id : "";
            return View();
        }

        public async Task<IActionResult> Expenses()
        {
            var applicationuser = await _userManager.GetUserAsync(HttpContext.User);
            ViewBag.ChefId = applicationuser.B2BInformation != null ? applicationuser.B2BInformation.Id : "";
            return View();
        }

        
    }
}

Travel1.0.0/Travel.UI/Areas/Report/Views/Management/Clients.cshtml
@{
    ViewBag.Title = "Customer Base Report";
}
<input type='hidden' id="CompanyId" value="@ViewBag.CompanyId" />
<div class="m-portlet m-portlet--mobile">
    <div class="m-portlet__head">
        <div class="m-portlet__head-caption m-portlet__head-label--danger">
            <div class="m-portlet__head-title">
                <span class="m-portlet__head-icon">
                    <i class="la la-gear" style="color:rgb(87, 89, 98);"></i>
                </span>
                <h3 class="m-portlet__head-text">
                    @ViewBag.Title
                </h3>
            </div>
        </div>
        <div class="m-portlet__head-tools">
            <ul class="m-portlet__nav"><li class="m-portlet__nav-item"></li></ul>
        </div>
    </div>

    <div class="m-portlet__body">

        <div class="m-form m-form--label-align-right m--margin-bottom-20">
            <div class="row">
                <div class="col-lg-3">
                    <label>Date Range:</label>
                    <input id="DateRange" type="text" class="form-control m-input m_maxlength_1_custom" maxlength="100" required="" placeholder="Enter date range">
                </div>
                <div class="col-lg-3 m--margin-top-15-tablet-and-mobile">
                    <label class="">Customer:</label>
                    <select id="CustomerId" class="form-control m-input m-input--air" required></select>
                </div>
                <div class="col-lg-4"></div>
                <div class="col-lg-2">
                    <label class="" style="color: white; width: 100%;">.</label>
                    <a id="show_report" href="#" onclick="javascript:getClientBasedPaymentStatus();" class="btn btn-primary m-btn m-btn--custom m-btn--icon m-btn--air m-btn--pill">
                        <span>
                            <i class="flaticon-line-graph"></i>
                            <span>Show Report</span>
                        </span>
                    </a>
                </div>
            </div>
        </div>

        <div class="m-form m-form--label-align-right m--margin-bottom-20">
            <!--begin: Datatable -->
            <div class="" id="add_data_table_row">
                @*<table class="table table-striped- table-bordered table-hover table-checkable dataTable no-footer dtr-inline" id="invoice_details_data_table" role="grid" aria-describedby="m_table_1_info" style="width: 979px;">
                    <thead>
                        <tr role="row">
                            <th class="sorting_asc" tabindex="0" aria-controls="m_table_1" rowspan="1" colspan="1" style="width: 221.25px !important;" aria-sort="ascending" aria-label="Agent: activate to sort column descending">Client</th>
                            <th class="sorting" tabindex="0" aria-controls="m_table_1" rowspan="1" colspan="1" style="width: 43.25px; text-align: right;" aria-label="Company Email: activate to sort column ascending"># Invoices</th>
                            <th class="sorting" tabindex="0" aria-controls="m_table_1" rowspan="1" colspan="1" style="width: 68.25px; text-align: right;" aria-label="Company Agent: activate to sort column ascending">Av. Invoice</th>
                            <th class="sorting" tabindex="0" aria-controls="m_table_1" rowspan="1" colspan="1" style="width: 133.25px; text-align: right;" aria-label="Company Name: activate to sort column ascending">Total</th>
                            <th class="sorting" tabindex="0" aria-controls="m_table_1" rowspan="1" colspan="1" style="width: 54.25px; text-align: right;" aria-label="Status: activate to sort column ascending">Received</th>
                            <th class="sorting" tabindex="0" aria-controls="m_table_1" rowspan="1" colspan="1" style="width: 110.25px; text-align: right;" aria-label="Type: activate to sort column ascending">Outstanding</th>
                        </tr>
                    </thead>
                    <tbody></tbody>
                </table>*@
            </div>
        </div>

    </div>

</div>

@Html.Hidden("loadCustomerUrl")

@section page_styles {
    <link href="~/assets/vendors/custom/datatables/datatables.bundle.css" rel="stylesheet" type="text/css" />
    <link href="~/vendors/bootstrap-daterangepicker/daterangepicker.css" rel="stylesheet" type="text/css" />
}

@section Scripts {
    <script src="~/assets/vendors/custom/datatables/datatables.bundle.js" type="text/javascript"></script>
    <script src="~/vendors/bootstrap-maxlength/src/bootstrap-maxlength.js" type="text/javascript"></script>
    <script src="~/assets/demo/custom/crud/forms/widgets/bootstrap-maxlength.js" type="text/javascript"></script>

    <script src="~/vendors/moment/min/moment.min.js" type="text/javascript"></script>
    <script src="~/vendors/bootstrap-daterangepicker/daterangepicker.js" type="text/javascript"></script>

    <script src="~/js/BlockUI_Custom.js"></script>
    <script src="~/js/report.js"></script>
    <script type="text/javascript">
        jQuery(document).ready(function () {

            $("#loadCustomerUrl").val("@(@Url.Action("LoadCustomer", "Management", new { Area = "Report"}))" + "/?CompanyId=" + $("#CompanyId").val());

            loadDashboardurl();
            initMenu("Report");
            loadCustomer();
            initInvoiceDetailsTable();

            $('#DateRange').daterangepicker({
                buttonClasses: 'm-btn btn',
                applyClass: 'btn-primary',
                cancelClass: 'btn-secondary'
            });

        });

    </script>

}

Travel1.0.0/Travel.UI/Areas/Report/Views/Management/Expenses.cshtml
@{
    ViewBag.Title = "Expenses Report";
}
<input type='hidden' id="CompanyId" value="@ViewBag.CompanyId"/>
<div class="m-portlet m-portlet--mobile">
    <div class="m-portlet__head">
        <div class="m-portlet__head-caption m-portlet__head-label--danger">
            <div class="m-portlet__head-title">
                <span class="m-portlet__head-icon">
                    <i class="la la-gear" style="color:rgb(87, 89, 98);"></i>
                </span>
                <h3 class="m-portlet__head-text">
                    @ViewBag.Title
                </h3>
            </div>
        </div>
        <div class="m-portlet__head-tools">
            <ul class="m-portlet__nav"><li class="m-portlet__nav-item"></li></ul>
        </div>
    </div>

    <div class="m-portlet__body">

        <div class="m-form m-form--label-align-right m--margin-bottom-20">
            <div class="form-group m-form__group row">
                <div class="col-lg-3">
                    <label>Date Range:</label>
                    <input id="DateRange" type="text" class="form-control m-input m_maxlength_1_custom" maxlength="100" required="" placeholder="Enter date range">
                </div>
                <div class="col-lg-3 m--margin-top-15-tablet-and-mobile">
                    <label class="">Vendor:</label>
                    <select id="Vendor" class="form-control m-input m-input--air" required></select>
                </div>
                <div class="col-lg-4 m--margin-top-15-tablet-and-mobile">
                    <label class="">Cateogry:</label>
                    <select id="Cateogry" class="form-control m-input m-input--air" required></select>
                </div>
                <div class="col-lg-2">
                    <label class="" style="color: white; width: 100%;">.</label>
                    <a id="show_report" href="#" onclick="javascript:getExpensesStatus();" class="btn btn-primary m-btn m-btn--custom m-btn--icon m-btn--air m-btn--pill">
                        <span>
                            <i class="flaticon-line-graph"></i>
                            <span>Show Report</span>
                        </span>
                    </a>
                </div>
            </div>
        </div>

        <div class="m-form m-form--label-align-right m--margin-bottom-20">
            <!--begin: Datatable -->
            <div class="" id="add_data_table_row">
                @*<table class="table table-striped- table-bordered table-hover table-checkable dataTable no-footer dtr-inline" id="invoice_details_data_table" role="grid" aria-describedby="m_table_1_info" style="width: 979px;">
                        <thead>
                            <tr role="row">
                                <th class="sorting_asc" tabindex="0" aria-controls="m_table_1" rowspan="1" colspan="1" style="width: 221.25px !important;" aria-sort="ascending" aria-label="Agent: activate to sort column descending">Client</th>
                                <th class="sorting" tabindex="0" aria-controls="m_table_1" rowspan="1" colspan="1" style="width: 43.25px; text-align: right;" aria-label="Company Email: activate to sort column ascending"># Invoices</th>
                                <th class="sorting" tabindex="0" aria-controls="m_table_1" rowspan="1" colspan="1" style="width: 68.25px; text-align: right;" aria-label="Company Agent: activate to sort column ascending">Av. Invoice</th>
                                <th class="sorting" tabindex="0" aria-controls="m_table_1" rowspan="1" colspan="1" style="width: 133.25px; text-align: right;" aria-label="Company Name: activate to sort column ascending">Total</th>
                                <th class="sorting" tabindex="0" aria-controls="m_table_1" rowspan="1" colspan="1" style="width: 54.25px; text-align: right;" aria-label="Status: activate to sort column ascending">Received</th>
                                <th class="sorting" tabindex="0" aria-controls="m_table_1" rowspan="1" colspan="1" style="width: 110.25px; text-align: right;" aria-label="Type: activate to sort column ascending">Outstanding</th>
                            </tr>
                        </thead>
                        <tbody></tbody>
                    </table>*@
            </div>
        </div>

    </div>

</div>

@Html.Hidden("loadVendorUrl")
@Html.Hidden("loadExpensesCategoryUrl")


@section page_styles {
    <link href="~/assets/vendors/custom/datatables/datatables.bundle.css" rel="stylesheet" type="text/css" />
    <link href="~/vendors/bootstrap-daterangepicker/daterangepicker.css" rel="stylesheet" type="text/css" />
}

@section Scripts {
    <script src="~/assets/vendors/custom/datatables/datatables.bundle.js" type="text/javascript"></script>
    <script src="~/vendors/bootstrap-maxlength/src/bootstrap-maxlength.js" type="text/javascript"></script>
    <script src="~/assets/demo/custom/crud/forms/widgets/bootstrap-maxlength.js" type="text/javascript"></script>

    <script src="~/vendors/moment/min/moment.min.js" type="text/javascript"></script>
    <script src="~/vendors/bootstrap-daterangepicker/daterangepicker.js" type="text/javascript"></script>

    <script src="~/js/BlockUI_Custom.js"></script>
    <script src="~/js/report.js"></script>
    <script type="text/javascript">
        jQuery(document).ready(function () {
            loadDashboardurl();
            initMenu("Report");

            loadExpensesCategory();
            loadVendor();

            initInvoiceDetailsTable();

            $('#DateRange').daterangepicker({
                buttonClasses: 'm-btn btn',
                applyClass: 'btn-primary',
                cancelClass: 'btn-secondary'
            });

        });

    </script>

}

Travel1.0.0/Travel.UI/Areas/Report/Views/Management/Index.cshtml
@{
    ViewBag.Title = "Company dashboard";
    //Layout = "_LayoutBackEnd";
}

<h2>Index</h2>

@section page_styles {
}

@section Scripts {
    <script type="text/javascript">
        jQuery(document).ready(function () {
            loadDashboardurl();
            initMenu("Report");
        });
    </script>

}

Travel1.0.0/Travel.UI/Areas/Report/Views/Management/Payments.cshtml
@{
    ViewBag.Title = "Payment Base Report";
}
<input type='hidden' id="CompanyId" value="@ViewBag.CompanyId"/>
<div class="m-portlet m-portlet--mobile">
    <div class="m-portlet__head">
        <div class="m-portlet__head-caption m-portlet__head-label--danger">
            <div class="m-portlet__head-title">
                <span class="m-portlet__head-icon">
                    <i class="la la-gear" style="color:rgb(87, 89, 98);"></i>
                </span>
                <h3 class="m-portlet__head-text">
                    @ViewBag.Title
                </h3>
            </div>
        </div>
        <div class="m-portlet__head-tools">
            <ul class="m-portlet__nav"><li class="m-portlet__nav-item"></li></ul>
        </div>
    </div>

    <div class="m-portlet__body">

        <div class="m-form m-form--label-align-right m--margin-bottom-20">
            <div class="form-group m-form__group row">
                <div class="col-lg-3">
                    <label>Date Range:</label>
                    <input id="DateRange" type="text" class="form-control m-input m_maxlength_1_custom" maxlength="100" required="" placeholder="Enter date range">
                </div>
                <div class="col-lg-3 m--margin-top-15-tablet-and-mobile">
                    <label class="">Customer:</label>
                    <select id="CustomerId" class="form-control m-input m-input--air" required></select>
                </div>
                <div class="col-lg-4 m--margin-top-15-tablet-and-mobile">
                    <label class="">Generate Report For:</label>
                    <select id="GenerateReportFor" class="form-control m-input m-input--air">
                        <option>Received Payments</option>
                        <option>Outstanding Payments</option>
                    </select>
                </div>
                <div class="col-lg-2">
                    <label class="" style="color: white; width: 100%;">.</label>
                    <a id="show_report" href="#" onclick="javascript:showReport();" class="btn btn-primary m-btn m-btn--custom m-btn--icon m-btn--air m-btn--pill">
                        <span>
                            <i class="flaticon-line-graph"></i>
                            <span>Show Report</span>
                        </span>
                    </a>
                </div>
            </div>
        </div>

        <div class="m-form m-form--label-align-right m--margin-bottom-20">
            <!--begin: Datatable -->
            <div class="" id="add_data_table_row">
                @*<table class="table table-striped- table-bordered table-hover table-checkable dataTable no-footer dtr-inline" id="invoice_details_data_table" role="grid" aria-describedby="m_table_1_info" style="width: 979px;">
                        <thead>
                            <tr role="row">
                                <th class="sorting_asc" tabindex="0" aria-controls="m_table_1" rowspan="1" colspan="1" style="width: 221.25px !important;" aria-sort="ascending" aria-label="Agent: activate to sort column descending">Client</th>
                                <th class="sorting" tabindex="0" aria-controls="m_table_1" rowspan="1" colspan="1" style="width: 43.25px; text-align: right;" aria-label="Company Email: activate to sort column ascending"># Invoices</th>
                                <th class="sorting" tabindex="0" aria-controls="m_table_1" rowspan="1" colspan="1" style="width: 68.25px; text-align: right;" aria-label="Company Agent: activate to sort column ascending">Av. Invoice</th>
                                <th class="sorting" tabindex="0" aria-controls="m_table_1" rowspan="1" colspan="1" style="width: 133.25px; text-align: right;" aria-label="Company Name: activate to sort column ascending">Total</th>
                                <th class="sorting" tabindex="0" aria-controls="m_table_1" rowspan="1" colspan="1" style="width: 54.25px; text-align: right;" aria-label="Status: activate to sort column ascending">Received</th>
                                <th class="sorting" tabindex="0" aria-controls="m_table_1" rowspan="1" colspan="1" style="width: 110.25px; text-align: right;" aria-label="Type: activate to sort column ascending">Outstanding</th>
                            </tr>
                        </thead>
                        <tbody></tbody>
                    </table>*@
            </div>
        </div>

    </div>

</div>

@Html.Hidden("loadCustomerUrl")

@section page_styles {
    <link href="~/assets/vendors/custom/datatables/datatables.bundle.css" rel="stylesheet" type="text/css" />
    <link href="~/vendors/bootstrap-daterangepicker/daterangepicker.css" rel="stylesheet" type="text/css" />
}

@section Scripts {
    <script src="~/assets/vendors/custom/datatables/datatables.bundle.js" type="text/javascript"></script>
    <script src="~/vendors/bootstrap-maxlength/src/bootstrap-maxlength.js" type="text/javascript"></script>
    <script src="~/assets/demo/custom/crud/forms/widgets/bootstrap-maxlength.js" type="text/javascript"></script>

    <script src="~/vendors/moment/min/moment.min.js" type="text/javascript"></script>
    <script src="~/vendors/bootstrap-daterangepicker/daterangepicker.js" type="text/javascript"></script>

    <script src="~/js/BlockUI_Custom.js"></script>
    <script src="~/js/report.js"></script>
    <script type="text/javascript">
        jQuery(document).ready(function () {

            $("#loadCustomerUrl").val("@(@Url.Action("LoadCustomer", "Management", new { Area = "Report"}))" + "/?CompanyId=" + $("#CompanyId").val());

            loadDashboardurl();
            initMenu("Report");
            loadCustomer();
            initInvoiceDetailsTable();

            $('#DateRange').daterangepicker({
                buttonClasses: 'm-btn btn',
                applyClass: 'btn-primary',
                cancelClass: 'btn-secondary'
            });

        });

    </script>

}